// ====================================================================================================
//
// Cloud Code for ChallengeCardModule, write your code here to customize the GameSparks platform.
//
// For details of the GameSparks Cloud Code API see https://docs.gamesparks.com/
//
// ====================================================================================================
require("ChallengeMovesModule");

const CARD_COLOR_NEUTRAL = 0;
const CARD_COLOR_FIRE = 1;
const CARD_COLOR_EARTH = 2;
const CARD_COLOR_WATER = 3;
const CARD_COLOR_DARK = 4;
const CARD_COLOR_LIGHT = 5;

const CARD_NAME_FIREBUG_CATELYN = "Firebug Catelyn";
const CARD_NAME_MARSHWATER_SQUEALER = "Marshwater Squealer";
const CARD_NAME_WATERBORNE_RAZORBACK = "Waterborne Razorback";
const CARD_NAME_BLESSED_NEWBORN = "Blessed Newborn";
const CARD_NAME_YOUNG_KYO = "Young Kyo";
const CARD_NAME_WAVE_CHARMER = "Wave Charmer";
const CARD_NAME_POSEIDONS_HANDMAIDEN = "Poseidon's Handmaiden";
const CARD_NAME_EMBERKITTY = "Emberkitty";
const CARD_NAME_FIRESTRIDED_TIGRESS = "Firestrided Tigress";
const CARD_NAME_TEMPLE_GUARDIAN = "Temple Guardian";
const CARD_NAME_BOMBSHELL_BOMBADIER = "Bombshell Bombadier";
const CARD_NAME_TAJI_THE_FEARLESS = "Taji the Fearless";
const CARD_NAME_UNKINDLED_JUNIOR = "Unkindled Junior";
const CARD_NAME_FLAMEBELCHER = "Flamebelcher";
const CARD_NAME_FIREBORN_MENACE = "Fireborn Menace";
const CARD_NAME_TEA_GREENLEAF = "Te'a Greenleaf";
const CARD_NAME_NESSA_NATURES_CHAMPION = "Nessa, Nature's Champion";
const CARD_NAME_BUBBLE_SQUIRTER = "Bubble Squirter";
const CARD_NAME_SWIFT_SHELLBACK = "Swift Shellback";
const CARD_NAME_SENTIENT_SEAKING = "Sentient Seaking";
const CARD_NAME_CRYSTAL_SNAPPER = "Crystal Snapper";
const CARD_NAME_BATTLECLAD_GASDON = "Battleclad Gasdon";
const CARD_NAME_REDHAIRED_PALADIN = "Redhaired Paladin";
const CARD_NAME_FIRESWORN_GODBLADE = "Firesworn Godblade";
const CARD_NAME_RITUAL_HATCHLING = "Ritual Hatchling";
const CARD_NAME_HELLBRINGER = "Hellbringer";
const CARD_NAME_HOOFED_LUSH = "Hoofed Lush";
const CARD_NAME_DIONYSIAN_TOSSPOT = "Dionysian Tosspot";
const CARD_NAME_SEAHORSE_SQUIRE = "Seahorse Squire";
const CARD_NAME_TRIDENT_BATTLEMAGE = "Trident Battlemage";
const CARD_NAME_SNEERBLADE = "Sneerblade";
const CARD_NAME_TIMEWARP_KINGPIN = "Timewarp Kingpin";
const CARD_NAME_LUX = "Lux";
const CARD_NAME_THUNDEROUS_DESPERADO = "Thunderous Desperado";
const CARD_NAME_CEREBOAROUS = "Cereboarus";
const CARD_NAME_GUPPEA = "Guppea";
const CARD_NAME_RHYNOKARP = "Rhynokarp";
const CARD_NAME_PRICKLEPILLAR = "Pricklepillar";
const CARD_NAME_ADDERSPINE_WEEVIL = "Adderspine Weevil";
const CARD_NAME_THIEF_OF_NIGHT = "Thief of Night";
const CARD_NAME_POWER_SIPHONER = "POWER Siphoner";
const CARD_NAME_LIL_RUSTY = "Lil' Rusty";
const CARD_NAME_INFERNO_902 = "INFERNO-902";
const CARD_NAME_CHAR_BOT_451 = "CHAR-BOT-451";
const CARD_NAME_MEGAPUNK = "MegaPUNK";
const CARD_NAME_DUSK_DWELLER = "Dusk Dweller";
const CARD_NAME_TALUSREAVER = "Talusreaver";
const CARD_NAME_PHANTOM_SKULLCRUSHER = "Phantom Skullcrusher";
const CARD_NAME_BLUE_GIPSY_V3 = "Blue Gipsy V3";
const CARD_NAME_FROSTLAND_THRASHER_8 = "Frostland THRASHER-8";
const CARD_NAME_CYBER_SENTINEL = "Cyber Sentinel";
const CARD_NAME_PAL_V1 = "PAL_V1";
const CARD_NAME_FORTRESS_KNIGHT = "Fortress Knight";
const CARD_NAME_TERRATANK = "Terratank";
const CARD_NAME_CULYSSA = "Culyssa";
const CARD_NAME_SABRE_CRYSTALLINE_DRAGON = "Sabre, Crystalline Dragon";
const CARD_NAME_SAPLET = "Saplet";
const CARD_NAME_FIRESMITH_APPRENTICE = "Firesmith Apprentice";
const CARD_NAME_FORGEMECH = "Forgemech";
const CARD_NAME_LIGHTHUNTER = "Lighthunter";
const CARD_NAME_BRINGER_OF_DAWN = "Bringer of Dawn";
const CARD_NAME_ABYSSAL_EEL = "Abyssal Eel";
const CARD_NAME_EMILIA_AIRHEART = "Emilia Airheart";
const CARD_NAME_PEARL_NYMPH = "Pearl Nymph";
const CARD_NAME_TARA_SWAN_PRINCESS = "Tara, Swan Princess";
const CARD_NAME_FROSTSPORE = "Frostspore";
const CARD_NAME_ANGELIC_EGG = "Angelic Egg";
const CARD_NAME_CURSED_EGG = "Cursed Egg";
const CARD_NAME_FOXY_APPRENTICE = "Foxy Apprentice";

const CARD_NAME_CHARGE_STRUCTURE = "Charge Structure";
const CARD_NAME_WARDENS_OUTPOST = "Warden's Outpost";
const CARD_NAME_COST_STRUCTURE = "Cost Structure";

const CARD_CREATURES = [
    CARD_NAME_FIREBUG_CATELYN,
    CARD_NAME_MARSHWATER_SQUEALER,
    CARD_NAME_WATERBORNE_RAZORBACK,
    CARD_NAME_BLESSED_NEWBORN,
    CARD_NAME_YOUNG_KYO,
    CARD_NAME_WAVE_CHARMER,
    CARD_NAME_POSEIDONS_HANDMAIDEN,
    CARD_NAME_EMBERKITTY,
    CARD_NAME_FIRESTRIDED_TIGRESS,
    CARD_NAME_TEMPLE_GUARDIAN,
    CARD_NAME_BOMBSHELL_BOMBADIER,
    CARD_NAME_TAJI_THE_FEARLESS,
    CARD_NAME_UNKINDLED_JUNIOR,
    CARD_NAME_FLAMEBELCHER,
    CARD_NAME_FIREBORN_MENACE,
    CARD_NAME_TEA_GREENLEAF,
    CARD_NAME_NESSA_NATURES_CHAMPION,
    CARD_NAME_BUBBLE_SQUIRTER,
    CARD_NAME_SWIFT_SHELLBACK,
    CARD_NAME_SENTIENT_SEAKING,
    CARD_NAME_CRYSTAL_SNAPPER,
    CARD_NAME_BATTLECLAD_GASDON,
    CARD_NAME_REDHAIRED_PALADIN,
    CARD_NAME_FIRESWORN_GODBLADE,
    CARD_NAME_RITUAL_HATCHLING,
    CARD_NAME_HELLBRINGER,
    CARD_NAME_HOOFED_LUSH,
    CARD_NAME_DIONYSIAN_TOSSPOT,
    CARD_NAME_SEAHORSE_SQUIRE,
    CARD_NAME_TRIDENT_BATTLEMAGE,
    CARD_NAME_SNEERBLADE,
    CARD_NAME_TIMEWARP_KINGPIN,
    CARD_NAME_LUX,
    CARD_NAME_THUNDEROUS_DESPERADO,
    CARD_NAME_CEREBOAROUS,
    CARD_NAME_GUPPEA,
    CARD_NAME_RHYNOKARP,
    CARD_NAME_PRICKLEPILLAR,
    CARD_NAME_ADDERSPINE_WEEVIL,
    CARD_NAME_THIEF_OF_NIGHT,
    CARD_NAME_POWER_SIPHONER,
    CARD_NAME_LIL_RUSTY,
    CARD_NAME_INFERNO_902,
    CARD_NAME_CHAR_BOT_451,
    CARD_NAME_MEGAPUNK,
    CARD_NAME_DUSK_DWELLER,
    CARD_NAME_TALUSREAVER,
    CARD_NAME_PHANTOM_SKULLCRUSHER,
    CARD_NAME_BLUE_GIPSY_V3,
    CARD_NAME_FROSTLAND_THRASHER_8,
    CARD_NAME_CYBER_SENTINEL,
    CARD_NAME_PAL_V1,
    CARD_NAME_FORTRESS_KNIGHT,
    CARD_NAME_TERRATANK,
    CARD_NAME_CULYSSA,
    CARD_NAME_SABRE_CRYSTALLINE_DRAGON,
    CARD_NAME_SAPLET,
    CARD_NAME_FIRESMITH_APPRENTICE,
    CARD_NAME_FORGEMECH,
    CARD_NAME_LIGHTHUNTER,
    CARD_NAME_BRINGER_OF_DAWN,
    CARD_NAME_ABYSSAL_EEL,
    CARD_NAME_EMILIA_AIRHEART,
    CARD_NAME_PEARL_NYMPH,
    CARD_NAME_TARA_SWAN_PRINCESS,
    CARD_NAME_FROSTSPORE,
    CARD_NAME_ANGELIC_EGG,
    CARD_NAME_CURSED_EGG,
    CARD_NAME_FOXY_APPRENTICE,
];

// Untargeted spells.
const CARD_NAME_BRR_BRR_BLIZZARD = "Brr Brr Blizzard";
const CARD_NAME_SHIELDS_UP = "Shields Up!";
const CARD_NAME_RAZE_TO_ASHES = "Raze to Ashes";
const CARD_NAME_GREEDY_FINGERS = "Greedy Fingers";
const CARD_NAME_SILENCE_THE_MEEK = "Silence the Meek";
const CARD_NAME_RALLY_TO_THE_QUEEN = "Rally to the Queen";
const CARD_NAME_BOMBS_AWAY = "Bombs Away";
const CARD_NAME_GRAVE_DIGGING = "Grave-digging";
const CARD_NAME_THE_SEVEN = "The Seven";
const CARD_NAME_BATTLE_ROYALE = "Battle Royale";

const CARD_SPELLS_UNTARGETED = [
    CARD_NAME_BRR_BRR_BLIZZARD,
    CARD_NAME_SHIELDS_UP,
    CARD_NAME_RAZE_TO_ASHES,
    CARD_NAME_GREEDY_FINGERS,
    CARD_NAME_SILENCE_THE_MEEK,
    CARD_NAME_RALLY_TO_THE_QUEEN,
    CARD_NAME_BOMBS_AWAY,
    CARD_NAME_GRAVE_DIGGING,
    CARD_NAME_THE_SEVEN,
    CARD_NAME_BATTLE_ROYALE,
];

// Targeted spells.
const CARD_NAME_TOUCH_OF_ZEUS = "Touch of Zeus";
const CARD_NAME_DEEP_FREEZE = "Deep Freeze";
const CARD_NAME_WIDESPREAD_FROSTBITE = "Widespread Frostbite";
const CARD_NAME_DEATH_NOTE = "Death Note";
const CARD_NAME_CONDEMN = "Condemn";

const CARD_NAME_UNSTABLE_POWER = "Unstable Power";
const CARD_NAME_BESTOWED_VIGOR = "Bestowed Vigor";

const CARD_SPELLS_TARGETED = [
    CARD_NAME_TOUCH_OF_ZEUS,
    CARD_NAME_DEEP_FREEZE,
    CARD_NAME_WIDESPREAD_FROSTBITE,
    CARD_NAME_DEATH_NOTE,
    CARD_NAME_CONDEMN,
    
    CARD_NAME_UNSTABLE_POWER,
    CARD_NAME_BESTOWED_VIGOR,
];

const CARD_SPELLS_TARGETED_OPPONENT_ONLY = [
    CARD_NAME_TOUCH_OF_ZEUS,
    CARD_NAME_DEEP_FREEZE,
    CARD_NAME_WIDESPREAD_FROSTBITE,
    CARD_NAME_DEATH_NOTE,
    CARD_NAME_CONDEMN,
];
const CARD_SPELLS_TARGETED_FRIENDLY_ONLY = [
    CARD_NAME_UNSTABLE_POWER,
    CARD_NAME_BESTOWED_VIGOR,
];
const CARD_SPELLS_TARGETED_BOTH = [

];
