// ====================================================================================================
//
// Cloud Code for ChallengeMovesModule, write your code here to customize the GameSparks platform.
//
// For details of the GameSparks Cloud Code API see https://docs.gamesparks.com/
//
// ====================================================================================================
const TIME_LIMIT_CATEGORY_NORMAL = "TIME_LIMIT_CATEGORY_NORMAL";
const TIME_LIMIT_CATEGORY_MULLIGAN = "TIME_LIMIT_CATEGORY_MULLIGAN";

const CHALLENGE_STATE_MODE_NORMAL = 0;
const CHALLENGE_STATE_MODE_MULLIGAN = 1;

const PLAYER_STATE_MODE_NORMAL = 0;
const PLAYER_STATE_MODE_MULLIGAN = 1;
const PLAYER_STATE_MODE_MULLIGAN_WAITING = 2;

const CARD_CATEGORY_MINION = 0;
const CARD_CATEGORY_SPELL = 1;
const CARD_CATEGORY_STRUCTURE = 2;

const MOVE_CATEGORY_PLAY_MULLIGAN = "MOVE_CATEGORY_PLAY_MULLIGAN";
const MOVE_CATEGORY_FINISH_MULLIGAN = "MOVE_CATEGORY_FINISH_MULLIGAN";
const MOVE_CATEGORY_SURRENDER_BY_CHOICE = "MOVE_CATEGORY_SURRENDER_BY_CHOICE";
const MOVE_CATEGORY_SURRENDER_BY_EXPIRE = "MOVE_CATEGORY_SURRENDER_BY_EXPIRE";
const MOVE_CATEGORY_CHALLENGE_OVER = "MOVE_CATEGORY_CHALLENGE_OVER"; // Mostly for testing purposes - playerId = winning player's ID.
const MOVE_CATEGORY_END_TURN = "MOVE_CATEGORY_END_TURN";
const MOVE_CATEGORY_DRAW_CARD = "MOVE_CATEGORY_DRAW_CARD";
const MOVE_CATEGORY_DRAW_CARD_MULLIGAN = "MOVE_CATEGORY_DRAW_CARD_MULLIGAN";
const MOVE_CATEGORY_DRAW_CARD_HAND_FULL = "MOVE_CATEGORY_DRAW_CARD_HAND_FULL";
const MOVE_CATEGORY_DRAW_CARD_DECK_EMPTY = "MOVE_CATEGORY_DRAW_CARD_DECK_EMPTY";
const MOVE_CATEGORY_PLAY_MINION = "MOVE_CATEGORY_PLAY_MINION";
const MOVE_CATEGORY_PLAY_SPELL_TARGETED = "MOVE_CATEGORY_PLAY_SPELL_TARGETED";
const MOVE_CATEGORY_PLAY_SPELL_UNTARGETED = "MOVE_CATEGORY_PLAY_SPELL_UNTARGETED";
const MOVE_CATEGORY_CARD_ATTACK = "MOVE_CATEGORY_CARD_ATTACK";
const MOVE_CATEGORY_RANDOM_TARGET = "MOVE_CATEGORY_RANDOM_TARGET";
const MOVE_CATEGORY_SUMMON_CREATURE = "MOVE_CATEGORY_SUMMON_CREATURE";
const MOVE_CATEGORY_SUMMON_CREATURE_FIELD_FULL = "MOVE_CATEGORY_SUMMON_CREATURE_FIELD_FULL";
const MOVE_CATEGORY_CONVERT_CREATURE = "MOVE_CATEGORY_CONVERT_CREATURE";

const CARD_ABILITY_CHARGE = 0;
const CARD_ABILITY_TAUNT = 1;
const CARD_ABILITY_SHIELD = 2;
const CARD_ABILITY_BOOST_FRIENDLY_ATTACK_BY_TEN = 3;
const CARD_ABILITY_BATTLE_CRY_DRAW_CARD = 4;
const CARD_ABILITY_LIFE_STEAL = 5;
const CARD_ABILITY_DEATH_RATTLE_DRAW_CARD = 6;
const CARD_ABILITY_END_TURN_HEAL_TEN = 7;
const CARD_ABILITY_END_TURN_HEAL_TWENTY = 8;
const CARD_ABILITY_END_TURN_DRAW_CARD = 9;
const CARD_ABILITY_DEATH_RATTLE_ATTACK_FACE_BY_TEN = 10;
const CARD_ABILITY_EACH_KILL_DRAW_CARD = 11;
const CARD_ABILITY_DEATH_RATTLE_ATTACK_RANDOM_THREE_BY_TWENTY = 12;
const CARD_ABILITY_END_TURN_ATTACK_IN_FRONT_BY_TEN = 13;
const CARD_ABILITY_END_TURN_ATTACK_IN_FRONT_BY_TWENTY = 14;
const CARD_ABILITY_BATTLE_CRY_ATTACK_IN_FRONT_BY_TEN = 15;
const CARD_ABILITY_BATTLE_CRY_ATTACK_IN_FRONT_BY_TWENTY = 16;
const CARD_ABILITY_DAMAGE_TAKEN_DAMAGE_PLAYER_FACE_BY_THIRTY = 17;
const CARD_ABILITY_BATTLE_CRY_SILENCE_IN_FRONT = 18;
const CARD_ABILITY_BATTLE_CRY_HEAL_FRIENDLY_MAX = 19;
const CARD_ABILITY_BATTLE_CRY_TAUNT_ADJACENT_FRIENDLY = 20;
const CARD_ABILITY_LETHAL = 21;
const CARD_ABILITY_ATTACK_DAMAGE_ADJACENT_BY_TEN = 22;
const CARD_ABILITY_ATTACK_DAMAGE_ADJACENT_BY_ATTACK = 23;
const CARD_ABILITY_BATTLE_CRY_DAMAGE_PLAYER_FACE_BY_TWENTY = 24;
const CARD_ABILITY_END_TURN_BOTH_PLAYERS_DRAW_CARD = 25;
const CARD_ABILITY_BATTLE_CRY_HEAL_ADJACENT_BY_TWENTY = 26;
const CARD_ABILITY_BATTLE_CRY_HEAL_ADJACENT_BY_FOURTY = 27;
const CARD_ABILITY_BATTLE_CRY_HEAL_ALL_CREATURES_BY_FOURTY = 28;
const CARD_ABILITY_BATTLE_CRY_REVIVE_HIGHEST_COST_CREATURE = 29; //
const CARD_ABILITY_DEATH_RATTLE_DAMAGE_ALL_OPPONENT_CREATURES_BY_TWENTY = 30;
const CARD_ABILITY_BATTLE_CRY_SILENCE_ALL_OPPONENT_CREATURES = 31;
const CARD_ABILITY_DEATH_RATTLE_DAMAGE_ALL_CREATURES_BY_THIRTY = 32;
const CARD_ABILITY_DEATH_RATTLE_ATTACK_FACE_BY_TWENTY = 33;
const CARD_ABILITY_DEATH_RATTLE_RESUMMON = 34;
const CARD_ABILITY_DEATH_RATTLE_SUMMON_DUSK_DWELLERS = 35;
const CARD_ABILITY_DEATH_RATTLE_SUMMON_SUMMONED_DRAGONS = 36;
const CARD_ABILITY_BATTLE_CRY_ATTACK_RANDOM_FROZEN_BY_TWENTY = 37;
const CARD_ABILITY_BATTLE_CRY_KILL_RANDOM_FROZEN = 38;
const CARD_ABILITY_PLAY_SPELL_DRAW_CARD = 39;
const CARD_ABILITY_END_TURN_BOOST_RANDOM_FRIENDLY_ZERO_TWENTY = 40;
const CARD_ABILITY_DAMAGE_TAKEN_ATTACK_FACE_BY_TWENTY = 41;
const CARD_ABILITY_ICY = 42;
const CARD_ABILITY_END_TURN_BOOST_RANDOM_FRIENDLY_TEN_TEN = 43;
const CARD_ABILITY_BATTLE_CRY_BOOST_ADJACENT_THIRTY_THIRTY = 44;
const CARD_ABILITY_PIERCING = 45;
const CARD_ABILITY_END_TURN_HEAL_FACE_THIRTY = 46;
const CARD_ABILITY_DOUBLE_STRIKE = 47;
const CARD_ABILITY_DEATH_RATTLE_HEAL_FRIENDLY_MAX = 48;
const CARD_ABILITY_DEATH_RATTLE_REVIVE_HIGHEST_COST_CREATURE = 49;
const CARD_ABILITY_BATTLE_CRY_HEAL_FACE_TWENTY = 50;

const VALID_ABILITIES = [
    CARD_ABILITY_CHARGE,
    CARD_ABILITY_TAUNT,
    CARD_ABILITY_SHIELD,
    CARD_ABILITY_BOOST_FRIENDLY_ATTACK_BY_TEN,
    CARD_ABILITY_BATTLE_CRY_DRAW_CARD,
    CARD_ABILITY_LIFE_STEAL,
    CARD_ABILITY_DEATH_RATTLE_DRAW_CARD,
    CARD_ABILITY_END_TURN_HEAL_TEN,
    CARD_ABILITY_END_TURN_HEAL_TWENTY,
    CARD_ABILITY_END_TURN_DRAW_CARD,
    CARD_ABILITY_DEATH_RATTLE_ATTACK_FACE_BY_TEN,
    CARD_ABILITY_EACH_KILL_DRAW_CARD,
    CARD_ABILITY_DEATH_RATTLE_ATTACK_RANDOM_THREE_BY_TWENTY,
    CARD_ABILITY_END_TURN_ATTACK_IN_FRONT_BY_TEN,
    CARD_ABILITY_END_TURN_ATTACK_IN_FRONT_BY_TWENTY,
    CARD_ABILITY_BATTLE_CRY_ATTACK_IN_FRONT_BY_TEN,
    CARD_ABILITY_BATTLE_CRY_ATTACK_IN_FRONT_BY_TWENTY,
    CARD_ABILITY_DAMAGE_TAKEN_DAMAGE_PLAYER_FACE_BY_THIRTY,
    CARD_ABILITY_BATTLE_CRY_SILENCE_IN_FRONT,
    CARD_ABILITY_BATTLE_CRY_HEAL_FRIENDLY_MAX,
    CARD_ABILITY_BATTLE_CRY_TAUNT_ADJACENT_FRIENDLY,
    CARD_ABILITY_LETHAL,
    CARD_ABILITY_ATTACK_DAMAGE_ADJACENT_BY_TEN,
    CARD_ABILITY_ATTACK_DAMAGE_ADJACENT_BY_ATTACK,
    CARD_ABILITY_BATTLE_CRY_DAMAGE_PLAYER_FACE_BY_TWENTY,
    CARD_ABILITY_END_TURN_BOTH_PLAYERS_DRAW_CARD,
    CARD_ABILITY_BATTLE_CRY_HEAL_ADJACENT_BY_TWENTY,
    CARD_ABILITY_BATTLE_CRY_HEAL_ADJACENT_BY_FOURTY,
    CARD_ABILITY_BATTLE_CRY_HEAL_ALL_CREATURES_BY_FOURTY,
    CARD_ABILITY_BATTLE_CRY_REVIVE_HIGHEST_COST_CREATURE,
    CARD_ABILITY_DEATH_RATTLE_DAMAGE_ALL_OPPONENT_CREATURES_BY_TWENTY,
    CARD_ABILITY_BATTLE_CRY_SILENCE_ALL_OPPONENT_CREATURES,
    CARD_ABILITY_DEATH_RATTLE_DAMAGE_ALL_CREATURES_BY_THIRTY,
    CARD_ABILITY_DEATH_RATTLE_ATTACK_FACE_BY_TWENTY,
    CARD_ABILITY_DEATH_RATTLE_RESUMMON,
    CARD_ABILITY_DEATH_RATTLE_SUMMON_DUSK_DWELLERS,
    CARD_ABILITY_DEATH_RATTLE_SUMMON_SUMMONED_DRAGONS,
    CARD_ABILITY_BATTLE_CRY_ATTACK_RANDOM_FROZEN_BY_TWENTY,
    CARD_ABILITY_BATTLE_CRY_KILL_RANDOM_FROZEN,
    CARD_ABILITY_PLAY_SPELL_DRAW_CARD,
    CARD_ABILITY_END_TURN_BOOST_RANDOM_FRIENDLY_ZERO_TWENTY,
    CARD_ABILITY_DAMAGE_TAKEN_ATTACK_FACE_BY_TWENTY,
    CARD_ABILITY_ICY,
    CARD_ABILITY_END_TURN_BOOST_RANDOM_FRIENDLY_TEN_TEN,
    CARD_ABILITY_BATTLE_CRY_BOOST_ADJACENT_THIRTY_THIRTY,
    CARD_ABILITY_PIERCING,
    CARD_ABILITY_END_TURN_HEAL_FACE_THIRTY,
    CARD_ABILITY_DOUBLE_STRIKE,
    CARD_ABILITY_DEATH_RATTLE_HEAL_FRIENDLY_MAX,
    CARD_ABILITY_DEATH_RATTLE_REVIVE_HIGHEST_COST_CREATURE,
    CARD_ABILITY_BATTLE_CRY_HEAL_FACE_TWENTY,
];

// Abilities that can be granted to other cards.
// If the grantor card dies, the granted abilities are lost.
const VALID_GRANTABLE_ABILITIES = [
    CARD_ABILITY_CHARGE,
    CARD_ABILITY_TAUNT,
    CARD_ABILITY_LIFE_STEAL,
    CARD_ABILITY_DOUBLE_STRIKE,
];

const BUFF_CATEGORY_INCREMENT_ATTACK = 1000;
const BUFF_CATEGORY_UNSTABLE_POWER = 1001;
const BUFF_CATEGORY_BESTOWED_VIGOR = 1002;
const BUFF_CATEGORY_ZERO_TWENTY = 1003;
const BUFF_CATEGORY_TEN_TEN = 1004;
const BUFF_CATEGORY_THIRTY_THIRTY = 1005;
const BUFF_CATEGORY_TWENTY_TWENTY = 1006;
const BUFF_CATEGORY_TEN_THIRTY = 1007;

const BUFF_HAND_DECREASE_COST_BY_COLOR = 2000;

const VALID_BUFF_FIELDS = [
    BUFF_CATEGORY_INCREMENT_ATTACK,
    BUFF_CATEGORY_UNSTABLE_POWER,
    BUFF_CATEGORY_BESTOWED_VIGOR,
    BUFF_CATEGORY_ZERO_TWENTY,
    BUFF_CATEGORY_TEN_TEN,
    BUFF_CATEGORY_THIRTY_THIRTY,
    BUFF_CATEGORY_TWENTY_TWENTY,
    BUFF_CATEGORY_TEN_THIRTY,
];

const TARGET_ID_FACE = "TARGET_ID_FACE";
