FROM amazonlinux

MAINTAINER Bob Chen <jtcdbob@gmail.com>

RUN yum install -y git gcc-c++

ENV NVM_DIR /root/.nvm

ENV NODE_VERSION 8.10

RUN mkdir $NVM_DIR \
    && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules

ENV PATH $NVM_DIR/v$NODE_VERSION/bin:$PATH
